#!/bin/zsh
#killem
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-wlr
killall xdg-desktop-portal

killall albert
killall dunst
killall hyprpaper
killall waybar

/usr/lib/xdg-desktop-portal-hyprland &
sleep 1
/usr/lib/xdg-desktop-portal &
export WLR_RENDERER=vulkan
export WLR_DRM_DEVICES=/dev/dri/card0
#Waybar
$HOME/.config/waybar/launch.sh -o vertical -s float -t catppuccin_mocha_black&
#KdeConnect
/usr/lib/kdeconnectd&
#Polkit
/usr/lib/polkit-kde-authentication-agent-1&
#Wallpaper
hyprpaper&
#Launcher
#QT_QPA_PLATFORM=xcb albert&
#Notifications
dunst&

