#!/bin/bash
#killem
killall albert
killall dunst
killall hyprpaper
killall waybar


#Waybar
$HOME/.config/waybar/launch.sh -o vertical -s float -t catppuccin_mocha_black&
#KdeConnect
/usr/lib/kdeconnectd&
#Polkit
/usr/lib/polkit-kde-authentication-agent-1&
#Wallpaper
hyprpaper&
#Launcher
QT_QPA_PLATFORM=xcb albert&
#Notifications
dunst&
