#!/bin/bash
cd ~
export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24
export SDL_VIDEODRIVER=wayland
export MOZ_ENABLE_WAYLAND=1
export WLR_RENDERER=vulkan
export WLR_EGL_NO_MODIFIERS=1

exec Hyprland
